Publish QoS profile from Filter-Id on Redis
dpdk-vbng-cp/accel-ppp pull request #10
Opened 2021-02-10 18:19 UTC by butjar

This PR allows passing of "QoS profiles" to accel-ppp via `Filter-Id` attributes in radius Access-Accept messages. The value of the Filter-Id is stored in accel-ppp's internal session struct and sent as `qos_val` attribute of the JOSN messages published on the redis bus. Following format is expected in the `Filter-Id` attribute: `<SERVICE_TYPE>/<DL_BITRATE_KBITS>/<UL_BITRATE_KBITS>`.

2021-02-10 18:33 UTC, micron10 commented
Thanks for this!

2021-02-10 18:34 UTC, butjar commented
> Thanks for this!

Not exactly what you asked for but maybe it's enough :).

2021-02-10 18:35 UTC, micron10 commented
yes its  enough :-)

On Wed, Feb 10, 2021, 20:35 Martin Fleischer <notifications@github.com>
wrote:

> Thanks for this!
>
> Not exactly what you asked for but maybe it's enough :).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/dpdk-vbng-cp/accel-ppp/pull/10#issuecomment-776921897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADCWD5FOQTEGZXYPYFJIIH3S6LGVLANCNFSM4XNN3JLQ>
> .
>

2021-02-10 18:36 UTC, butjar commented
> yes its enough :-)
> […](#)
> On Wed, Feb 10, 2021, 20:35 Martin Fleischer ***@***.***> wrote: Thanks for this! Not exactly what you asked for but maybe it's enough :). — You are receiving this because you commented. Reply to this email directly, view it on GitHub <[#10 (comment)](https://github.com/dpdk-vbng-cp/accel-ppp/pull/10#issuecomment-776921897)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ADCWD5FOQTEGZXYPYFJIIH3S6LGVLANCNFSM4XNN3JLQ> .

:sunglasses:

2021-02-10 18:37 UTC, micron10 commented
other do you have options to kntegratw dpdk to accel ot netmap

On Wed, Feb 10, 2021, 20:35 Martin Zaharinov <micron10@gmail.com> wrote:

> yes its  enough :-)
>
> On Wed, Feb 10, 2021, 20:35 Martin Fleischer <notifications@github.com>
> wrote:
>
>> Thanks for this!
>>
>> Not exactly what you asked for but maybe it's enough :).
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/dpdk-vbng-cp/accel-ppp/pull/10#issuecomment-776921897>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADCWD5FOQTEGZXYPYFJIIH3S6LGVLANCNFSM4XNN3JLQ>
>> .
>>
>

2021-02-10 18:41 UTC, butjar commented
> other do you have options to kntegratw dpdk to accel ot netmap

We use accel-ppp as control plane for a DPDK based dataplane. The redis bus helps us to configure the dataplane, it is the purpose of this whole fork :).

2021-02-10 18:44 UTC, micron10 commented
hm.. via kni interface and manual up vlan to dpdk . and how connect pppoe
to accel is pppoe interface up on dpdk or ?
do you have telegram

On Wed, Feb 10, 2021, 20:41 Martin Fleischer <notifications@github.com>
wrote:

> other do you have options to kntegratw dpdk to accel ot netmap
>
> We use accel-ppp as control plane for a DPDK based dataplane. The redis
> bus helps us to configure the dataplane, it is the purpose of this whole
> fork :).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/dpdk-vbng-cp/accel-ppp/pull/10#issuecomment-776925584>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADCWD5BE6KDEHK5TJOCZSCLS6LHMZANCNFSM4XNN3JLQ>
> .
>

2021-02-10 18:52 UTC, butjar commented
> hm.. via kni interface and manual up vlan to dpdk . and how connect pppoe to accel is pppoe interface up on dpdk or ? do you have telegram

[Here](https://www.bisdn.de/#products) you can find a talk from ONF spotlight and a white paper about the solution we are working on. Best is to get in contact via email.

2021-02-11 18:42 UTC, butjar commented
# Test instructions
## Publishing `Filter-Id` values to redis (e536ed96b9a5ec1074ab0e089c7b5599856490cf)

### Requirements
- Radius setup with `Filter-Id` Attributes returned on *Access-Accept* e.g. by adding `Filter-Id` entries to the `radreply` table for freeradius with `rlm_sql` (https://wiki.freeradius.org/guide/SQL-HOWTO-for-freeradius-3.x-on-Debian-Ubuntu#populating-sql)
- An accel-ppp instance connected to a running redis-server
- `redis-cli`
- `accel-ppp.conf` with `redis` module enabled and a config similar to the following (with **ev_radius_access_accept=yes** enabled):
    ```
    ...
    redis
    ...
    [redis]
    host=redis
    port=6379
    pubchan=accel-ppp

    # select the event types to emit a message via redis
    ev_ses_starting=yes
    ev_ses_finishing=yes
    ev_ses_finished=yes
    ev_ses_pre_finished=yes
    ev_ses_acct_start=yes
    ev_radius_access_accept=yes
    ```
  
### Test steps
1. Connect `redis-cli` to the running redis instance and subscribe to the `accel-ppp` channel:
    ```
    $ redis-cli 
        127.0.0.1:6379> SUBSCRIBE accel-ppp
        Reading messages... (press Ctrl-C to quit)
        1) "subscribe"
        2) "accel-ppp"
        3) (integer) 1

    ```
2. Create a client session:
    ```
    $ pppd pty "pppoe -I <IFACE> -T 80 -U -m 1350" \
        noccp \
        ipparam <IFACE> \
        linkname <IFACE> \
        noipdefault \
        noauth \
        default-asyncmap \
        defaultroute \
        hide-password \
        updetach \
        mtu 1350 \
        mru 1350 \
        noaccomp \
        nodeflate \
        nopcomp \
        novj \
        novjccomp \
        lcp-echo-interval 40 \
        lcp-echo-failure 3 \
        user <PPP_USER> \
        password <PPP_PASWORD>
    ```

### Expected behavior
The `Filter-Id` should be published in the messages on the `accel-ppp` channel as `qos_val`:

```
127.0.0.1:6379> SUBSCRIBE accel-ppp
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "accel-ppp"
3) (integer) 1
1) "message"
2) "accel-ppp"
3) "{ \"event\": \"session-starting\", \"ctrl_type\": \"pppoe\", \"channel_name\": \"aa:aa:aa:aa:00:c8\", \"session_id\": \"d89da8604fc10e66\", \"called_station_id\": \"06:9d:98:10:37:7e\", \"calling_station_id\": \"aa:aa:aa:aa:00:c8\", \"name\": \"pppoe\", \"ip_addr\": \"\", \"pppoe_sessionid\": 1, \"ctrl_ifname\": \"vethAC.7.200\", \"nas_identifier\": \"nas1\" }"
1) "message"
2) "accel-ppp"
3) "{ \"event\": \"radius-access-accept\", \"ctrl_type\": \"pppoe\", \"channel_name\": \"aa:aa:aa:aa:00:c8\", \"session_id\": \"d89da8604fc10e66\", \"called_station_id\": \"06:9d:98:10:37:7e\", \"calling_station_id\": \"aa:aa:aa:aa:00:c8\", \"name\": \"pppoe\", \"ip_addr\": \"\", \"pppoe_sessionid\": 1, \"ctrl_ifname\": \"vethAC.7.200\", \"nas_identifier\": \"nas1\", \"qos_val\": \"1\\/16000\\/2000\" }"
1) "message"
2) "accel-ppp"
3) "{ \"event\": \"session-acct-start\", \"ctrl_type\": \"pppoe\", \"channel_name\": \"aa:aa:aa:aa:00:c8\", \"session_id\": \"d89da8604fc10e66\", \"called_station_id\": \"06:9d:98:10:37:7e\", \"calling_station_id\": \"aa:aa:aa:aa:00:c8\", \"name\": \"pppoe\", \"username\": \"sp-tin\", \"ip_addr\": \"192.51.0.3\", \"pppoe_sessionid\": 1, \"ctrl_ifname\": \"vethAC.7.200\", \"nas_identifier\": \"nas1\", \"qos_val\": \"1\\/16000\\/2000\" }"
```

2021-02-12 13:07 UTC, rr-santos commented
8540ddb992ab2ad70965c04beadbd41c821d9536 and 64ca45d7a1db067c7d411509682dcbb5f6585d80 seem to be addressing an issue different from the original goal of this PR. I suggest that these two are separated into a different PR to facilitate testing and match the description of the branches to be merged.

2021-02-12 14:33 UTC, butjar commented
> [8540ddb](https://github.com/dpdk-vbng-cp/accel-ppp/commit/8540ddb992ab2ad70965c04beadbd41c821d9536) and [64ca45d](https://github.com/dpdk-vbng-cp/accel-ppp/commit/64ca45d7a1db067c7d411509682dcbb5f6585d80) seem to be addressing an issue different from the original goal of this PR. I suggest that these two are separated into a different PR to facilitate testing and match the description of the branches to be merged.

I see the point for separate PRs, however the commits modify the same files and I wanted to avoid the overhead of rebasing several PRs against each other (possible conflicts + building container images etc.). I have cleanly separated the concerns in several commits. The description states the different purposes included in this PR. Many merge messages with duplicated content (the changes are documented in the commits) also make the history a bit more confusing. The PR could indicate a new release of our fork.

2021-02-12 15:16 UTC, rr-santos commented
The description of the PR clearly states that the PR addresses 3 different issues, 2 of them unrelated to the original PR title, Publish QoS profile from Filter-Id on Redis. While I understand the convenience of including everything together, this makes the reviewing/testing process more complicated. Please separate the additional commits previously mentioned into a separate MR.

2021-02-12 15:50 UTC, rr-santos requested changes
See https://github.com/dpdk-vbng-cp/accel-ppp/pull/10#issuecomment-778255337

2021-02-12 17:40 UTC, closed without merging